# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering of the workflow from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Leo-apu

      # Check the status of the repository (useful for debugging)
      - name: Check git status
        run: git status

      # Push the generated files to the output branch
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake animation"
          git push origin +HEAD:output

      # Deploy to GitHub Pages (if you want to publish the generated snake)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
